version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Forward port 80 on the client to 80 on the container.
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - registration

  registration:
    build: ./services/registration
    volumes:
      - ./services/registration:/usr/src/app/registration:ro  # Copy local source code as read only.
    working_dir: /usr/src/app/registration
    environment:  # Config settings to load AFTER the entry point of the container.
      - PYTHONPATH="$PYTHONPATH:/usr/src/app:/usr/local/lib:/usr/local/bin"
    expose:
      - "8000"
    entrypoint: gunicorn registration.wsgi --config=./gunicorn.py
    
  postgres:
    image: postgres:10-alpine
    volumes:
      # Allows persistent data by syncing the local dir with the container's dir.
      - ./postgres-data:/var/lib/postgresql  # /var/lib/postgresql/data is the default for PGDATA variable.
    environment:
      - POSTGRES_PASSWORD=tmp  # Only other containers on this server have access since we do not expose ports.
