# Notes:
#  - 'volumes' are not respected by Heroku.
#  - Exposed ports are not respected by Heroku either.  Apps must get $PORT instead.

version: '3'
services:
  registration:
    build: ./services/registration
    volumes:
      - ./services/registration:/usr/src/app/registration:ro  # Copy local source code as read only.
    working_dir: /usr/src/app/registration
    environment:  # Config settings to load AFTER the entry point of the container.
      - PYTHONPATH="$PYTHONPATH:/usr/src/app:/usr/local/lib:/usr/local/bin"
      - DEPLOYMENT_MODE=prod
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cruzhacks_db
      - IS_WHITELIST_ENABLED=True
      - MAILCHIMP_ATTENDEE_LIST=sourdough
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:10-alpine
    volumes:
      # Allows persistent data by syncing the local dir with the container's dir.
      - ./postgres/data:/var/lib/postgresql/data  # /var/lib/postgresql/data is the default for PGDATA variable.
    environment:
      - POSTGRES_PASSWORD=password  # This is only used for local testing so it doesn't matter.
      - POSTGRES_DB=cruzhacks_db
    ports:
      - "5432:5432"
    restart: always
