version: 2

jobs:
  test:
    environment:
      PYTHONPATH: ./services
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            export PYTHONPATH="$PYTHONPATH:$PWD"
            for service in $(ls -d services/*/); do reqs=${service%?}/requirements.txt; if [[ -e $reqs ]]; then sudo pip install -r $reqs; fi; done
            pytest
            echo "Tests Completed"

  lint:
    environment:
      PYTHONPATH: ./services
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Check Code For Style Compliance
          command: |
            echo "Running Linter"
            for service in $(ls -d services/*/); do reqs=${service%?}/requirements.txt; if [[ -e $reqs ]]; then sudo pip install -r $reqs; pylint --rcfile=.pylintrc $service; fi; done
            echo "Linting Completed"

workflows:
  version: 2
  lint_and_test:
    jobs:
      - test
      - lint

